### ISSUE TITLE
20-1 A Generation of Lifelong Learners

### ISSUE THREAD

**Issue by hewigovens** [objccn/articles#311]

**Comment by aprilnov** [comment]
占一个~

**Comment by onevcat** [comment]
@aprilnov 因为这一期内容比较特殊，文章标题的话也请贴切文章内容进行翻译或者拟定。参考标题《终身学习的一代人》

**Comment by aprilnov** [comment]
收到~

**Comment by aprilnov** [comment]
已翻，求 review..
觉得比技术文档翻译起来难多了...T_T

**Comment by onevcat** [comment]
:+1: 
哈..因为技术文档用词就那么几个，也不会有什么惯用说法..口语和日常的翻译确实比较难..

现在比较忙，下午的时候看一下。

**Comment by onevcat** [comment]
@aprilnov 完成审核准备发布

请提供一个简单的个人简介和一个网址链接，用来放在译文后面。另外如果必要的话请提供一个头像（或者就直接使用 Github 的头像）

**Comment by aprilnov** [comment]
“做 iOS / Mac / Web 开发的大白羊小妹儿~”  头像就用 GitHub 的就行。

**Comment by onevcat** [comment]
已发布 http://objccn.io/issue-20-1/
