### ISSUE TITLE
20-2 Something Slightly Less Terrible

### ISSUE THREAD

**Issue by hewigovens** [objccn/articles#312]

**Comment by zengyun-programmer** [comment]
认领～求带走

—曾赟
iOS DeveloperEmail: zengyun.programmer@gmail.com

**Comment by onevcat** [comment]
@zengyun-programmer  因为这一期内容比较特殊，文章标题的话也请贴切文章内容进行翻译或者拟定。参考标题《让东西不那么糟》

**Comment by zengyun-programmer** [comment]
@onevcat 收到~

**Comment by zengyun-programmer** [comment]
@onevcat 在喵神催稿之前主动汇报一下进度。目前63%。目测今天晚上到明天可以翻译完~

**Comment by onevcat** [comment]
。。。63%，这么精确啊..

**Comment by zengyun-programmer** [comment]
@onevcat 因为用的Google译者工具包。翻译进度和字数一目了然~

**Comment by onevcat** [comment]
好先进..

**Comment by weekwood** [comment]
涨知识了。。。

**Comment by zengyun-programmer** [comment]
咦大家都不知道？赶紧来安利下。在[Google翻译](http://translate.google.cn/?hl=zh)的页面上点击下方的译者工具包即可。输入文章网址，译者工具包会自动先帮你机翻一边，翻译的过程中还能自动匹配Google翻译库。另外添加标注和多人协作都很方便。好了说了这么多了我感觉我要来不及了赶紧去翻译了

**Comment by aprilnov** [comment]
玩了一下，发现专业翻译要$100+.. 顿时觉得胸前的红领巾更鲜艳了~

2015-01-21 10:04 GMT+08:00 zengyun-programmer <notifications@github.com>:

> 咦大家都不知道？赶紧来安利下。在Google翻译 <http://translate.google.cn/?hl=zh>
> 的页面上点击下方的译者工具包即可。输入文章网址，译者工具包会自动先帮你机翻一边，翻译的过程中还能自动匹配Google翻译库。另外添加标注和多人协作都很方便。好了说了这么多了我感觉我要来不及了赶紧去翻译了
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/objccn/articles/issues/312#issuecomment-70772291>.
>



-- 
Regards and thanks,
April Peng.

**Comment by zengyun-programmer** [comment]
所以我等屌丝一般都是选择自己翻译……

**Comment by zengyun-programmer** [comment]
进度播报。已经翻译完，赶着吃饭还不能提交。晚上吃完饭来提交。大家见谅。

**Comment by zengyun-programmer** [comment]
已OK。

**Comment by onevcat** [comment]
Published
