### ISSUE TITLE
20-3 Infinite Things to Learn

### ISSUE THREAD

**Issue by hewigovens** [objccn/articles#313]

**Comment by hewigovens** [comment]
我喜欢这个萌妹子, 认领啦

**Comment by zengyun-programmer** [comment]
啊哈。被提前一步—曾赟
iOS DeveloperEmail: zengyun.programmer@gmail.com

**Comment by onevcat** [comment]
@hewigovens  因为这一期内容比较特殊，文章标题的话也请贴切文章内容进行翻译或者拟定。参考标题《学无止境》

**Comment by hewigovens** [comment]
@onevcat 👌

**Comment by onevcat** [comment]
Published http://objccn.io/issue-20-3/
