### ISSUE TITLE
21-1 How Your Camera Works

### ISSUE THREAD

**Issue by bifidy** [objccn/articles#330]
http://www.objc.io/issue-21/how-your-camera-works.html

这篇略偏硬件，相机与物理专业术语略多貌似= =文章较长，楼下加油~

**Comment by bifidy** [comment]
这篇略偏硬件，相机与物理专业术语略多貌似= =文章较长，楼下加油~

**Comment by onevcat** [comment]
这篇我来吧~

**Comment by onevcat** [comment]
已发布 http://objccn.io/issue-21-1/
