### ISSUE TITLE
21-2 Image Formats

### ISSUE THREAD

**Issue by bifidy** [objccn/articles#331]
http://www.objc.io/issue-21/image-formats.html

**Comment by bifidy** [comment]
鉴于这篇比较短比较简单，如无异议，小的就先占了~
按照一周翻译时限，截至2月19日前提交

**Comment by onevcat** [comment]
@bifidy 催稿催稿..2月19日已经过去很久了..

**Comment by bifidy** [comment]
额= =虽然说起来觉得不太可信，但是留言占坑的时候完全没意识到2月19日是大年初一ಥ_ಥ
已提 p-r 才过来斗胆致歉，自立flag什么的死的最惨了= =

**Comment by onevcat** [comment]
当时给我感动的啊...（不放假的可怜人就等着review了，结果没有...）

**Comment by bifidy** [comment]
m(_ _)m 小的知错了...自罚三杯，以儆效尤_(´ཀ`」 ∠)_
