### ISSUE TITLE
21-3 Camera Capture on iOS

### ISSUE THREAD

**Issue by bifidy** [objccn/articles#332]
http://www.objc.io/issue-21/camera-capture-on-ios.html

**Comment by bifidy** [comment]
高能预警：这篇的示例代码是 swift ，代码讲解部分希望不会吃力~楼下加油~

**Comment by nathanwhy** [comment]
抢~

**Comment by onevcat** [comment]
@nathanwhy 
校对完成，可以发布。
请提供一个简短的个人简介和一个链接，将会放到译文后面。谢谢~

**Comment by nathanwhy** [comment]
抱歉来晚了
iOS开发者，兴趣广泛，正不断尝试新的挑战。
http://nathanwhy.github.io/

**Comment by onevcat** [comment]
Never mind. Thanks. :)

**Comment by onevcat** [comment]
Published http://objccn.io/issue-21-3/
