### ISSUE TITLE
21-4 The Photos Framework

### ISSUE THREAD

**Issue by bifidy** [objccn/articles#333]
http://www.objc.io/issue-21/the-photos-framework.html

这篇涉及到了 iOS 8 的新特性： PhotoKit，之前不熟悉的话可能要做额外预习工作，楼下加油~

**Comment by bifidy** [comment]
这篇涉及到了 iOS 8 的新特性： PhotoKit，之前不熟悉的话可能要做额外预习工作，楼下加油~

**Comment by CrazyZombies** [comment]
边学边翻，这篇给我了

**Comment by onevcat** [comment]
@CrazyZombies 拜个晚年，新春快乐..顺便催个稿..

**Comment by CrazyZombies** [comment]
不好意思，春节琐碎的东西太多，家里没网不方便，这几天赶下工。

**Comment by CrazyZombies** [comment]
更新下进度，初翻完毕，明天再校对下上传。
早上还有那么多没翻译完，现在就剩我一个，压力好大 [抠鼻]

**Comment by CrazyZombies** [comment]
我试了下 clone repo，那个 origin 的文件夹没法 clone 下来，查了下好像是多项目合作之用。不知道会不会影响上传？

**Comment by weekwood** [comment]
不会

**Comment by CrazyZombies** [comment]
@weekwood 谢谢，已 PR

**Comment by CrazyZombies** [comment]
第一次翻译，水平有限，多多包涵！
