### ISSUE TITLE
21-5 Photo Extensions

### ISSUE THREAD

**Issue by bifidy** [objccn/articles#334]
http://www.objc.io/issue-21/photo-extensions.html

iOS 8 的照片扩展，记得翻译注释哦~ 楼下加油~

**Comment by bifidy** [comment]
iOS 8 的照片扩展，swift 代码片段，记得翻译 注释~ 楼下加油~

**Comment by weekwood** [comment]
有人来其他人优先，没人来我来。

**Comment by onevcat** [comment]
嗯，这期比较多，估计人排不过来。

**Comment by onevcat** [comment]
@weekwood HIHI，我来催稿了..
