### ISSUE TITLE
21-7 GPU-Accelerated Image Processing

### ISSUE THREAD

**Issue by bifidy** [objccn/articles#336]
http://www.objc.io/issue-21/gpu-accelerated-image-processing.html

**Comment by nangege** [comment]
这篇我来吧

**Comment by onevcat** [comment]
@nangege 春节快乐~~我来催稿了..

**Comment by nangege** [comment]
过年在家没网，不方便，昨天晚上刚回。已经翻译完了，今天再校对下，晚上发。   春节快乐。
