### ISSUE TITLE
21-8 GPU-Accelerated Machine Vision 

### ISSUE THREAD

**Issue by bifidy** [objccn/articles#337]
http://www.objc.io/issue-21/gpu-accelerated-machine-vision.html

粗略的看了下（其实是没看懂），这篇因为涉及到了图像识别，会有一些图形算法相关的东西，觉得如果没有基础的话会比较难，无论如何，楼下加油~

**Comment by dopcn** [comment]
占了，居然是 GPUImage 的作者写的

**Comment by onevcat** [comment]
@dopcn 当当当..我又催稿来了//

**Comment by dopcn** [comment]
最后一节了今晚搞定:joy:
