### ISSUE TITLE
21-9 Face Recognition with OpenCV

### ISSUE THREAD

**Issue by bifidy** [objccn/articles#338]
http://www.objc.io/issue-21/face-recognition-with-opencv.html

**Comment by Phenmod** [comment]
昨天还在搞车牌识别，今天就有脸部识别的文章。。。。
已读完，已照文章把工程做完。
求带走。

**Comment by Phenmod** [comment]
求带走。
谁让我最近在做车牌识别呢。。。

**Comment by Phenmod** [comment]
在原文下添加了译文。
代码没有复制粘贴一份，而是把原文代码后面 ``` 后的语言指定如 "c"、"objc"去掉了。
图片使用的原文图片。

请校对辛苦。
回家过年去也。

祝大家新年快乐。

**Comment by Phenmod** [comment]
哦 文章名翻译为：“基于 OpenCV 的人脸识别”

人脸识别算是大家叫熟了口的惯用法，脸孔识别怪怪的。

**Comment by onevcat** [comment]
@Phenmod 
校对完毕，如果还有空的话还请麻烦看一下。没问题/没回应的话明天发布。

春节快乐~

**Comment by onevcat** [comment]
已发布 http://objccn.io/issue-21-9/
