### ISSUE TITLE
需要找到一个方式同步修复 objc.io 的 issues 的方式

### ISSUE THREAD

**Issue by weekwood** [objccn/articles#339]
objc.io 的文章中的 bug 经常会得到提及以及很好的修正，而我们需要找到一个合理的方式来同步所有的修复，或者手动搬运。
各位有什么建议可以提。

**Comment by dopcn** [comment]
上 https://ifttt.com 大法
if 
any new issues or new pr in objc/articles 
then 
create a new issue in objccn/articles

**Comment by weekwood** [comment]
我不确定是不是同步所有的issues 是一个好办法。但是你的确给我了我一个启发 @dopcn 
@onevcat 如果我们创建一个 trello todo 列表或者 slack 来抓取 objc.io 的新issue 列表如何？任何成员可以针对提交PR

**Comment by weekwood** [comment]
我觉得现在的数量我可以手动完成这个工作。
