### ISSUE TITLE
22-5 React-Inspired Views

### ISSUE THREAD

**Issue by zengyun-programmer** [objccn/articles#365]
http://www.objc.io/issue-22/facebook.html

**Comment by lizixroy** [comment]
I got this one!

**Comment by zengyun-programmer** [comment]
hi~ 要翻译完了才能关闭哟

**Comment by lizixroy** [comment]
origin中并没有本期的原文。 我需要等到原文放上来之后再翻译吗？ 
根据“如何贡献”似乎我只能在别的地方先写好译文然后等到原文上来之后一段一段复制上去让后提交pull-request.

**Comment by onevcat** [comment]
Published
