### ISSUE TITLE
23-2 Core Image and Video

### ISSUE THREAD

**Issue by bifidy** [objccn/articles#386]
原文：http://www.objc.io/issue-23/core-image-video.html
Markdown：https://github.com/objcio/articles/blob/master/2015-04-13-core-image-video.md

**Comment by pupboss** [comment]
我来翻译吧

**Comment by pupboss** [comment]
http://img.objccn.io/issue-23/camera.m4v 这个视频没有抓下来

**Comment by pupboss** [comment]
http://img.objccn.io/issue-23/flow.svg  这个图像不存在

**Comment by pupboss** [comment]
翻译完了，已 pull request

**Comment by onevcat** [comment]
感谢提交。图像和视频已经更新。回头review。

**Comment by pupboss** [comment]
恩好的，还有个事，刚才我擅做主张把一个 pull request 给 merge 了，本来是想试下成员有哪些权限的。。。

**Comment by onevcat** [comment]
T-T..啊，那没办法了。我回头再处理一下吧。Github 的话没有那么多权限限制，普通的 git 操作只要是 contributor 就都能做。

**Comment by pupboss** [comment]
添麻烦了...是这个  https://github.com/objccn/articles/pull/388 在 master 分支，有五处改动，都是语法方面的

**Comment by onevcat** [comment]
Published.
