### ISSUE TITLE
23-3 Video Toolbox and Hardware Acceleration

### ISSUE THREAD

**Issue by bifidy** [objccn/articles#387]
原文：http://www.objc.io/issue-23/videotoolbox.html
Markdown：https://github.com/objcio/articles/blob/master/2015-04-13-videotoolbox.md

**Comment by pupboss** [comment]
没人翻还是我来吧，不过质量和时效比不上第一篇了

**Comment by onevcat** [comment]
没关系，慢一点就好，请保证翻译质量。

**Comment by pupboss** [comment]
收到

**Comment by pupboss** [comment]
这篇也翻译完了，确实比第一次顺利一些

**Comment by onevcat** [comment]
Published.
