### ISSUE TITLE
24-4 Audio API Overview

### ISSUE THREAD

**Issue by Draveness** [objccn/articles#397]
我来翻这个吧

**Comment by bifidy** [comment]
帮助补齐链接与更新状态：
原文:http://www.objc.io/issue-24/audio-api-overview.html
Markdown:https://github.com/objcio/articles/blob/master/2015-05-11-audio-api-overview.markdown

**Comment by onevcat** [comment]
@Draveness  需要您的个人简介和一个网址，用来放在文后

**Comment by Draveness** [comment]
个人简介: 一直都在挖坑 网址: deltax.me
