### ISSUE TITLE
24-1 The Audio Processing Dog House

### ISSUE THREAD

**Issue by bifidy** [objccn/articles#398]
原文:http://www.objc.io/issue-24/audio-dog-house.html
Markdown:https://github.com/objcio/articles/blob/master/2015-05-11-audio-dog-house.md

**Comment by aprilnov** [comment]
居然还剩.. 顺走...

**Comment by onevcat** [comment]
这篇里面有一些 js 的内容，留在那里不动就可以了，稍后我来处理。
