### ISSUE TITLE
无法向mail@objccn.io发送邮件

### ISSUE THREAD

**Issue by buginux** [objccn/articles#413]
是不是现在已经不接受新的翻译人员加入了？我向mail@objccn.io发送了申请邮件，但是一直提示我邮件被对方服务器退回。这是为神马呢，我好希望能够加入的。TAT

**Comment by pupboss** [comment]
上个月不知道什么原因，英文版站点没更新，同时网站也改版了，不知道是出于什么目的

**Comment by buginux** [comment]
哦哦，那意思就是说现在中文版的也没办法更新了是么。那希望到时恢复的时候能再加我一个啊。：）

**Comment by pupboss** [comment]
这个需要联系 Owner @onevcat 我没权限 哈哈

**Comment by bifidy** [comment]
两件事说明下：
1.翻译人员的加入并没有固定的组织维护，文章的翻译认领只是根据 objc.io 文章更新后对相关 issue 的认领。
2. objc.io 已于6月初网站改版，至于什么时候出新期刊，还会不会出新期刊，暂时没有更官方的消息。所以可以暂时理解为翻译工作已截止于 objc.io 停止更新 = =

剩余关注点参见楼下解释~

**Comment by buginux** [comment]
(｡•́︿•̀｡)喔，晓得了，看来真是bad time了，刚想进就遇上停刊了。

**Comment by onevcat** [comment]
现在 objc.io 的期刊已经完结停载了，所以暂时 objc 中国也不会有新的任务，所以现在也不再添加成员。
如果您想对项目进行贡献的话，可以考虑阅读和检查已有期刊，并且帮助修正错误。欢迎您将修正以 pull request 的形式发给我们。

**Comment by buginux** [comment]
好的，明白了，感谢喵神的回复。：）

**Comment by Phenmod** [comment]
见[http://www.objc.io/about/](http://www.objc.io/about/) 最后一段，以后只写长篇了，不知道还会不会出期刊，估计以后也像 raywenderlich 那样出书卖了。
>
> After two years of publishing an issue every month, we decided to take a break and to focus on some
> more long-form writing. We published our first book – Functional Programming in Swift – in late 2014,
> and we’re currently working on two new books: Advanced Swift and Core Data.

**Comment by buginux** [comment]
(｡•́︿•̀｡)看来确实是这样了，看样子最近一段时间应该不会再出issue了，真可惜了。他们的issue都是极好的，最近要改写书了。

**Comment by aprilnov** [comment]
其实也可以吧，如果他们授权，可以免费翻译中文版嘛，还可以先睹为快...（我是不是想的太好了....）

**Comment by buginux** [comment]
照你这么个说法，如果真能这样，想想还真是有点小激动啊，ㄟ(▔ ,▔)ㄏ。
