### ISSUE TITLE
issue-3-1的一个小错误

### ISSUE THREAD

**Issue by ming-qdu** [objccn/articles#414]
《绘制像素到屏幕上》中第四段有一句话：“不同的GPU是不同的性能怪兽，但是驱动使他们在下一个层级上显示的更为统一，***典型的驱动有 OpenGL/OpenGL ES***“，意思翻译错了。原文的意思是：”典型的下一层级有 OpenGL/OpenGL ES“。

原文：Different GPUs are different beasts, and the driver makes them appear more uniform to the next layer, which is typically OpenGL / OpenGL ES.

**Comment by wongzigii** [comment]
您好，你可以根据这个issue提交一个Pull Request。

**Comment by ming-qdu** [comment]
抱歉，现在还太会用Git，正在学习中。

**Comment by answer-huang** [comment]
感谢，我来改一下。
