### ISSUE TITLE
申请换个人简介中的链接

### ISSUE THREAD

**Issue by dopcn** [objccn/articles#432]
由于之前使用的域名彻底过期也不再使用了所以希望能换一些 objccn 上译者简介部分的链接。我搜了一下这个数据似乎并没有直接保存在这个 repo 里不能直接 PR 修改，所以麻烦喵神改一下，多谢

包含需要改动的文章链接：
http://objccn.io/issue-17-2/
http://objccn.io/issue-19-5/
http://objccn.io/issue-21-8/

个人简介链接改为：http://blog.fengweizhou.com/

**Comment by onevcat** [comment]
好的，我稍后处理。感谢！

**Comment by onevcat** [comment]
应该搞定了，请确认一下。

**Comment by dopcn** [comment]
确认都改了，多谢喵神:clap:
