### ISSUE TITLE
http://objccn.io/ 打不开了

### ISSUE THREAD

**Issue by ChenTF** [objccn/articles#448]
hi, 我发现http://objccn.io/  打不开了, 然后看到本git库下有相关文章, 同时也找到了https://github.com/objccn/articles/blob/master/SUMMARY.md  这个目录, 可并不完善. 

可否完善一下呢?

**Comment by onevcat** [comment]
打不开请自行翻墙…中国部分地区和网络商下打不开

**Comment by ChenTF** [comment]
翻墙后还是打不开, 我打开google, facebook没问题..

**Comment by onevcat** [comment]
可以确认一下 objccn.io 在不在你的代理适用的列表里。或者直接用全局翻墙。

对于这个问题我们几乎无能为力。另外，也可以访问一下 http://downforeveryoneorjustme.com/objccn.io 看看 objccn.io 是不是确实 down 了还是只是你访问不了。

**Comment by ChenTF** [comment]
额.. 确实设置成全局代理就可以了. 
乌龙了, 抱歉.

**Comment by ampm** [comment]
![image](https://user-images.githubusercontent.com/1634096/54340689-e6912a00-4672-11e9-9490-2db8658d1933.png)
objccn.io is down , 无法下载之前购买的书
