### ISSUE TITLE
“Mach-O 可执行文件”文章中一个拼写错误

### ISSUE THREAD

**Issue by jiaxw32** [objccn/articles#450]
[Mach-O 可执行文件](https://objccn.io/issue-6-3/)文中“ 符号表和链接”小节中的拼写错误：

原文：
> 每个函数、全局变量和类等都是通过符号的形式来定义和使用的。当我们将目标文件链接为一个可执行文件时，链接器 (ld(1)) 在目标文件盒动态库之间对符号做了解析处理。

“链接器 (ld(1)) 在目标文件盒动态库之间对符号做了解析处理” 中“盒”拼写错误，应该为“和”

英文：
> Each function, global variable, class, etc. that is defined or used results in a symbol. When we link object files into an executable, the linker (ld(1)) resolves symbols as needed between object files and dynamic libraries.

**Comment by onevcat** [comment]
要考虑发个 P-R 么？
